### ISSUE TITLE
TypeError: use() got an unexpected keyword argument 'warn'

### ISSUE THREAD

**Issue by pinpss** [pmorissette/ffn#122]
Dear Philippe,

I don't know if this error is related to ffn or Matplotlib. But  I only receive the error message with the ffn package. 

The same issue has been reported here, however, their solution doesn't work for my case.
[https://github.com/conchoecia/pauvre/issues/18](url)

`import ffn
Traceback (most recent call last):

  File "<ipython-input-199-9d4b951d98c0>", line 1, in <module>
    import ffn

  File "/Users/mc/opt/anaconda3/lib/python3.8/site-packages/ffn/__init__.py", line 1, in <module>
    from . import core

  File "/Users/mc/opt/anaconda3/lib/python3.8/site-packages/ffn/core.py", line 27, in <module>
    matplotlib.use('agg', warn=False)

TypeError: use() got an unexpected keyword argument 'warn'`

Any advices?

**Comment by timkpaine** [comment]
Duplicate and fixed on master

**Comment by mbabatunde** [comment]
Hi,

I'm also having this same issue and I tried downgrading my matplotlib library, but that didn't fix the issue. 
Is there something I'm missing?
